/**
 * §13.11 — `enable` and `disable` (rows 117–131).
 *
 * The tool has to be findable on `PATH` for the default install directory to
 * resolve (§10.4), so each fixture plants an executable `pipack` in a throwaway
 * directory and puts it first on `PATH`. `enable` writes its stubs next to the
 * library entry module, so these rows run a *copy* of `src/` and leave the
 * checkout alone.
 */

import {
  chmodSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  readlinkSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import { cleanupFixtures, copyTool, createFixture, run } from "./_harness/index.ts";

const TOOL = copyTool();

const IS_WINDOWS = process.platform === "win32";

/** A directory on `PATH` holding our own binary — where shims belong by default. */
function toolOnPath() {
  const fixture = createFixture();
  const binDir = join(fixture.root, "bin");
  mkdirSync(binDir, { recursive: true });
  writeFileSync(join(binDir, "pipack"), "#!/bin/sh\nexit 0\n");
  chmodSync(join(binDir, "pipack"), 0o755);

  return {
    fixture,
    binDir,
    /** `run()` options that make `<binDir>` the natural shim directory. */
    options: {
      cwd: fixture.cwd,
      home: fixture.home,
      bin: TOOL,
      env: { PATH: `${binDir}:${process.env.PATH ?? ""}` },
    },
  };
}

afterAll(cleanupFixtures);

describe("§13.11 enable / disable", () => {
  it("117: enable installs a shim for every non-npm package manager beside the tool", async () => {
    const { binDir, options } = toolOnPath();

    const result = await run(["enable"], options);

    expect(result.exitCode).toBe(0);
    expect(result.stdout).toBe("");
    expect(result.stderr).toBe("");
    for (const name of ["yarn", "yarnpkg", "pnpm", "pnpx"]) {
      expect(lstatSync(join(binDir, name)).isSymbolicLink()).toBe(true);
    }
    for (const name of ["npm", "npx"]) {
      expect(() => lstatSync(join(binDir, name))).toThrow();
    }
  });

  it("118: enable --install-directory puts the shims there instead", async () => {
    const { fixture, options } = toolOnPath();
    const target = join(fixture.root, "elsewhere");
    mkdirSync(target);

    const result = await run(["enable", "--install-directory", target], options);

    expect(result.exitCode).toBe(0);
    expect(lstatSync(join(target, "yarn")).isSymbolicLink()).toBe(true);
    expect(lstatSync(join(target, "pnpm")).isSymbolicLink()).toBe(true);
  });

  it("119: enable --install-directory=<dir> yarn installs yarn and yarnpkg only", async () => {
    const { fixture, options } = toolOnPath();
    const target = join(fixture.root, "only-yarn");
    mkdirSync(target);

    const result = await run(["enable", `--install-directory=${target}`, "yarn"], options);

    expect(result.exitCode).toBe(0);
    expect(lstatSync(join(target, "yarn")).isSymbolicLink()).toBe(true);
    expect(lstatSync(join(target, "yarnpkg")).isSymbolicLink()).toBe(true);
    expect(() => lstatSync(join(target, "pnpm"))).toThrow();
  });

  it.skipIf(IS_WINDOWS)(
    "120: enable replaces a plain file that is one of our own stubs",
    async () => {
      const { binDir, options } = toolOnPath();
      // A shim we wrote earlier, copied rather than linked — §14.16 recognises it
      // by its marker and replaces it; a *foreign* file is row 121's case.
      writeFileSync(
        join(binDir, "yarn"),
        "#!/usr/bin/env node\n// @pipack-shim — generated by `pipack enable`\n",
      );

      const result = await run(["enable"], options);

      expect(result.exitCode).toBe(0);
      expect(result.stderr).toBe("");
      expect(lstatSync(join(binDir, "yarn")).isSymbolicLink()).toBe(true);
    },
  );

  it.skipIf(IS_WINDOWS)(
    "121: enable refuses a foreign regular file unless --force (§14.16)",
    async () => {
      const { binDir, options } = toolOnPath();
      const foreign = "#!/bin/sh\necho a real yarn\n";
      writeFileSync(join(binDir, "yarn"), foreign);

      const refused = await run(["enable"], options);

      expect(refused.exitCode).toBe(0);
      expect(refused.stderr).toContain("was not installed by this tool");
      expect(refused.stderr).toContain("use --force to overwrite");
      expect(readFileSync(join(binDir, "yarn"), "utf8")).toBe(foreign);
      expect(lstatSync(join(binDir, "yarn")).isSymbolicLink()).toBe(false);
      // Its siblings are still installed.
      expect(lstatSync(join(binDir, "pnpm")).isSymbolicLink()).toBe(true);

      const forced = await run(["enable", "--force"], options);
      expect(forced.exitCode).toBe(0);
      expect(lstatSync(join(binDir, "yarn")).isSymbolicLink()).toBe(true);
    },
  );

  it.skipIf(IS_WINDOWS)(
    "122: enable is idempotent — a correct symlink is not rewritten",
    async () => {
      const { binDir, options } = toolOnPath();
      expect((await run(["enable"], options)).exitCode).toBe(0);
      const before = lstatSync(join(binDir, "yarn"));

      const again = await run(["enable"], options);

      expect(again.exitCode).toBe(0);
      const after = lstatSync(join(binDir, "yarn"));
      expect(after.mtimeMs).toBe(before.mtimeMs);
      expect(after.ino).toBe(before.ino);
    },
  );

  it.skipIf(IS_WINDOWS)("123: enable corrects a symlink pointing elsewhere", async () => {
    const { binDir, fixture, options } = toolOnPath();
    const stray = join(fixture.root, "stray.js");
    writeFileSync(stray, "");
    symlinkSync(stray, join(binDir, "yarn"));

    const result = await run(["enable"], options);

    expect(result.exitCode).toBe(0);
    expect(result.stderr).toBe("");
    expect(readlinkSync(join(binDir, "yarn"))).not.toBe(stray);
    expect(readlinkSync(join(binDir, "yarn"))).toContain("yarn.js");
  });

  it.skipIf(IS_WINDOWS)("124: enable skips a Yarn Switch install and says so", async () => {
    const { binDir, fixture, options } = toolOnPath();
    const switchBin = join(fixture.root, "switch", "bin");
    mkdirSync(switchBin, { recursive: true });
    writeFileSync(join(switchBin, "yarn.js"), "");
    symlinkSync(join(switchBin, "yarn.js"), join(binDir, "yarn"));

    const result = await run(["enable"], options);

    expect(result.exitCode).toBe(0);
    expect(result.stderr).toMatch(
      /^yarn is already installed in .+ and points to a Yarn Switch install - skipping\n$/,
    );
    expect(readlinkSync(join(binDir, "yarn"))).toBe(join(switchBin, "yarn.js"));
  });

  it("125: disable removes the shims and leaves everything else alone", async () => {
    const { binDir, options } = toolOnPath();
    writeFileSync(join(binDir, "unrelated"), "#!/bin/sh\n");
    expect((await run(["enable"], options)).exitCode).toBe(0);

    const result = await run(["disable"], options);

    expect(result.exitCode).toBe(0);
    expect(result.stderr).toBe("");
    for (const name of ["yarn", "yarnpkg", "pnpm", "pnpx"]) {
      expect(() => lstatSync(join(binDir, name))).toThrow();
    }
    expect(lstatSync(join(binDir, "pipack")).isFile()).toBe(true);
    expect(lstatSync(join(binDir, "unrelated")).isFile()).toBe(true);
  });

  it("126: disable --install-directory=<dir> yarn removes yarn and yarnpkg only", async () => {
    const { fixture, options } = toolOnPath();
    const target = join(fixture.root, "shims");
    mkdirSync(target);
    expect((await run(["enable", `--install-directory=${target}`], options)).exitCode).toBe(0);

    const result = await run(["disable", `--install-directory=${target}`, "yarn"], options);

    expect(result.exitCode).toBe(0);
    expect(() => lstatSync(join(target, "yarn"))).toThrow();
    expect(() => lstatSync(join(target, "yarnpkg"))).toThrow();
    expect(lstatSync(join(target, "pnpm")).isSymbolicLink()).toBe(true);
  });

  it.skipIf(IS_WINDOWS)(
    "127: disable skips a Yarn Switch install with the same warning",
    async () => {
      const { binDir, fixture, options } = toolOnPath();
      const switchBin = join(fixture.root, "switch", "bin");
      mkdirSync(switchBin, { recursive: true });
      writeFileSync(join(switchBin, "yarn.js"), "");
      symlinkSync(join(switchBin, "yarn.js"), join(binDir, "yarn"));

      const result = await run(["disable", "yarn"], options);

      expect(result.exitCode).toBe(0);
      expect(result.stderr).toMatch(
        /^yarn is already installed in .+ and points to a Yarn Switch install - skipping\n$/,
      );
      expect(lstatSync(join(binDir, "yarn")).isSymbolicLink()).toBe(true);
    },
  );

  it.skipIf(!IS_WINDOWS)(
    "128: on Windows the same entry is removed without a warning",
    async () => {
      // Windows-only by construction (§10.2 makes the Switch guard POSIX-only). The
      // platform-independent generator is asserted from POSIX by
      // test/unit/shims.test.ts::"128: Windows removal takes the same entry ...".
      const { binDir, fixture, options } = toolOnPath();
      const switchBin = join(fixture.root, "switch", "bin");
      mkdirSync(switchBin, { recursive: true });
      writeFileSync(join(switchBin, "yarn.js"), "");
      writeFileSync(join(binDir, "yarn"), "");

      const result = await run(["disable", "yarn"], options);

      expect(result.exitCode).toBe(0);
      expect(result.stderr).toBe("");
      expect(() => lstatSync(join(binDir, "yarn"))).toThrow();
    },
  );

  it("129: disable on a directory with no shims succeeds", async () => {
    const { fixture, options } = toolOnPath();
    const empty = join(fixture.root, "empty");
    mkdirSync(empty);

    const first = await run(["disable", `--install-directory=${empty}`], options);
    const second = await run(["disable", `--install-directory=${empty}`], options);

    expect(first.exitCode).toBe(0);
    expect(first.stderr).toBe("");
    expect(second.exitCode).toBe(0);
  });

  it("130: enable rejects a name that is not a package manager", async () => {
    const { binDir, options } = toolOnPath();

    const result = await run(["enable", "cargo"], options);

    expect(result.exitCode).toBe(1);
    expect(result.stdout).toContain(`Usage Error: Invalid package manager name 'cargo'`);
    expect(result.stdout).toContain("$ corepack enable");
    expect(() => lstatSync(join(binDir, "yarn"))).toThrow();
  });

  it.skipIf(!IS_WINDOWS)("131: on Windows enable writes <B>, <B>.cmd and <B>.ps1", async () => {
    // Windows-only by construction; the three bodies are compared byte for byte
    // from POSIX by test/unit/shims.test.ts::"131: writes <B>, <B>.cmd and <B>.ps1".
    const { binDir, options } = toolOnPath();

    const result = await run(["enable", "yarn"], options);

    expect(result.exitCode).toBe(0);
    for (const suffix of ["", ".cmd", ".ps1"]) {
      expect(lstatSync(join(binDir, `yarn${suffix}`)).isFile()).toBe(true);
    }
  });
});
