/**
 * §08.3.3 — build `native/execve.zig` for every host jup runs on and embed the
 * results in `src/run/addon-binaries.ts`.
 *
 * The addon ships *inside the bundle*, not beside it: jup has no runtime
 * dependencies and no per-platform packages, and `enable` writes the one file
 * this host needs into `<home>` (§07.2) when it installs shims. Each binary is
 * stored zstd-compressed and base64-encoded, alongside the SHA-256 of the bytes
 * `enable` must end up writing, which is also the extracted file's name. Mach-O
 * pads its segments to 16 KiB pages, so the zeros go first; zstd then beats
 * deflate by about a tenth and decodes as fast, where brotli's few percent more
 * cost twice the decode.
 *
 * The output is committed, like the table refresh's: a checkout builds and
 * tests without Zig, and a change to the addon is a reviewable diff. Zig is
 * pinned, because a different compiler emits different bytes.
 *
 * Usage (`pnpm build:addon` runs the same thing):
 *   node scripts/build-addon.mjs           # rebuild and rewrite
 *   node scripts/build-addon.mjs --check   # rebuild; exit 1 if the committed file differs
 *
 * CI runs `--check`, so the committed bytes are the ones this source builds: a
 * digest checked only against bytes beside it proves nothing about either.
 */

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { constants, zstdCompressSync } from "node:zlib";

const ROOT = join(import.meta.dirname, "..");
const SOURCE = join(ROOT, "native", "execve.zig");
const OUTPUT = join(ROOT, "src", "run", "addon-binaries.ts");

const ZIG_VERSION = "0.16.0";

/**
 * `<process.platform>-<process.arch>` → Zig target, for §02.4's POSIX hosts less
 * Intel macOS, which is legacy: a Mac without a build keeps the relay and
 * `process.execve`, as any host without one does.
 */
const TARGETS = {
  "darwin-arm64": "aarch64-macos",
  "linux-arm64": "aarch64-linux",
  "linux-x64": "x86_64-linux",
};

const check = process.argv.includes("--check");

const zig = process.env.ZIG ?? "zig";
const version = execFileSync(zig, ["version"], { encoding: "utf8" }).trim();
if (version !== ZIG_VERSION) {
  console.error(`build-addon: needs zig ${ZIG_VERSION}, found ${version}`);
  process.exit(1);
}

const work = mkdtempSync(join(tmpdir(), "jup-addon-"));
const entries = [];
try {
  for (const [host, target] of Object.entries(TARGETS)) {
    // A relative name in a directory of its own: Mach-O records the emitted
    // path as the install name, and a temp directory there changes the bytes.
    const cwd = join(work, host);
    mkdirSync(cwd);
    const file = join(cwd, "execve.node");
    execFileSync(
      zig,
      [
        "build-lib",
        "-dynamic",
        "-O",
        "ReleaseSmall",
        "-fstrip",
        // Node-API symbols resolve against the process that loads the addon.
        "-fallow-shlib-undefined",
        "-target",
        target,
        SOURCE,
        "-femit-bin=execve.node",
      ],
      { cwd, stdio: "inherit" },
    );
    const bytes = readFileSync(file);
    entries.push({
      host,
      sha256: createHash("sha256").update(bytes).digest("hex"),
      size: bytes.length,
      zstd: zstdCompressSync(bytes, {
        params: { [constants.ZSTD_c_compressionLevel]: 19 },
      }).toString("base64"),
    });
  }
} finally {
  rmSync(work, { recursive: true, force: true });
}

const body = [
  "// Generated by `pnpm build:addon` (scripts/build-addon.mjs) from native/execve.zig",
  `// with zig ${ZIG_VERSION}; edits are overwritten.`,
  "",
  "/** §08.3.3 — one addon per host: its SHA-256, byte length, and zstd-compressed bytes. */",
  "export const ADDON_BINARIES: Record<string, { sha256: string; size: number; zstd: string }> = {",
  ...entries.flatMap(({ host, sha256, size, zstd }) => [
    `  "${host}": {`,
    `    sha256: "${sha256}",`,
    `    size: ${size},`,
    `    zstd: "${zstd}",`,
    "  },",
  ]),
  "};",
  "",
].join("\n");

let current = "";
try {
  current = readFileSync(OUTPUT, "utf8");
} catch {
  // First build.
}
for (const { host, sha256, size } of entries) console.log(`${host}  ${size} bytes  ${sha256}`);

if (check) {
  if (current !== body) {
    console.error(`build-addon: ${OUTPUT} is stale; run \`pnpm build:addon\``);
    process.exit(1);
  }
} else {
  writeFileSync(OUTPUT, body);
}
