/**
 * Compile the tool to a single native binary with `scriptc`, experimentally.
 *
 * [`scriptc`](https://scriptc.dev) type-checks with the real TypeScript
 * compiler, lowers the program to LLVM IR and links a small native runtime, so
 * the result runs with no Node.js on the machine. That is the shape §16.1 wants
 * for a proxy invocation — a static binary has no interpreter to boot and no
 * module graph to resolve — so this script exists to *measure how far the source
 * is from getting there*. It is not part of `pnpm build`: the shipped artifact
 * is still `dist/`, and nothing here is on the release path.
 *
 * `scriptc` compiles a whole TypeScript program itself, following static imports
 * and honouring the nearest `tsconfig.json`, so the source goes in unbundled and
 * keeps its types — which is the point, since types are what it lowers. Three
 * generated files in `.scriptc/` are all it needs:
 *
 *   - `entry.ts` — `src/bin.ts` with the `import()` of `main.ts` made static.
 *     A dynamic import is a *dynamic site*: `scriptc` will not follow it, so the
 *     real entry compiles to three statements and a call into an engine that a
 *     static build does not contain. The lazy cold path (§01.3) buys startup
 *     time for a module loader that a compiled binary does not have.
 *   - `globals.d.ts` — `HeadersInit`, which `src/net/proxy.ts` takes from
 *     `lib.dom`, absent from `scriptc`'s lib set.
 *   - `tsconfig.json` — the root config, flattened.
 *
 * Usage:
 *   node scripts/compile.mjs               # build .scriptc/pipack
 *   node scripts/compile.mjs --coverage    # what fraction lowers statically
 *   node scripts/compile.mjs --dynamic     # embed quickjs-ng (~620 KB)
 *   node scripts/compile.mjs -o /tmp/pk    # choose the output path
 *   node scripts/compile.mjs -- --emit-ir  # forward flags to scriptc
 *
 * Cross-compiling is `scriptc`'s contract, not ours — its env passes through:
 *   SCRIPTC_CC=zigcc SCRIPTC_TARGET=wasm32-wasi node scripts/compile.mjs
 *
 * `--dynamic` embeds a JS engine to run what does not lower, which sounds like
 * the way to get a binary today and is not: it pulls the cold path (§01.3) into
 * the program, and its blockers with it. Static is the default here as it is
 * upstream.
 *
 * **What this measures is the warm path only.** Everything past an `import()`
 * is unreachable to `scriptc` and therefore unjudged; `compile-transform.mjs`
 * makes those imports static and reports the whole-program number, which is
 * three times larger. Read that one for the honest total.
 *
 * `scriptc` is deliberately *not* a dependency of this package — it is an
 * experiment, and a zero-dependency tool should not grow an 86 MB devDependency
 * to satisfy one. If it is not installed the script runs it through `npx`.
 */

import { mkdir, stat, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { argv, exit, stdout } from "node:process";
import {
  flattenedTsconfig,
  GLOBALS_DTS,
  outDir,
  preflight,
  rel,
  root,
  runScriptc,
} from "./scriptc.mjs";

const args = argv.slice(2);
const split = args.indexOf("--");
const forwarded = split === -1 ? [] : args.slice(split + 1);
const own = split === -1 ? args : args.slice(0, split);

const flag = (...names) => own.some((arg) => names.includes(arg));
const option = (...names) => {
  const at = own.findIndex((arg) => names.includes(arg));
  return at === -1 ? undefined : own[at + 1];
};

if (flag("-h", "--help")) {
  stdout.write(
    [
      "Usage: node scripts/compile.mjs [options] [-- <scriptc flags>]",
      "",
      "  -o, --out <path>  Output binary (default .scriptc/pipack)",
      "      --coverage    Report what lowers statically; emit no binary",
      "      --dynamic     Embed quickjs-ng for what does not lower",
      "      --prepare     Write .scriptc/ and stop, without invoking scriptc",
      "  -h, --help        This message",
      "",
    ].join("\n"),
  );
  exit(0);
}

const out = resolve(root, option("-o", "--out") ?? join(outDir, "pipack"));
const entry = join(outDir, "entry.ts");

preflight();

// -------------------------------------------------------------- 1. generate

await mkdir(outDir, { recursive: true });

await writeFile(
  entry,
  `// Generated by scripts/compile.mjs — do not edit.
//
// src/bin.ts, with two changes scriptc needs and Node does not:
//   - main.ts is imported statically, so the program is one compiled unit
//     rather than a call into an engine this build may not contain;
//   - the exit code goes through process.exit, because assignment to a member
//     expression — process.exitCode = n — has no lowering yet (SC1090).
/// <reference path="./globals.d.ts" />

import { runMain } from "../src/main.ts";

// §05.5/§10.1 — the tool's own entry point defaults the prompt off; written out
// rather than \`??=\`, which scriptc does not lower on member expressions.
if (process.env.COREPACK_ENABLE_DOWNLOAD_PROMPT === undefined) {
  process.env.COREPACK_ENABLE_DOWNLOAD_PROMPT = "0";
}

process.exit(await runMain(process.argv.slice(2)));
`,
);

await writeFile(join(outDir, "globals.d.ts"), GLOBALS_DTS);
await writeFile(
  join(outDir, "tsconfig.json"),
  await flattenedTsconfig(["./entry.ts", "./globals.d.ts", "../src/**/*.ts"]),
);

console.log(`Wrote ${rel(outDir)}/{entry.ts,globals.d.ts,tsconfig.json}`);

if (flag("--prepare")) exit(0);

// --------------------------------------------------------------- 2. compile

const invocation = flag("--coverage")
  ? ["coverage", entry]
  : ["build", entry, "-o", out, ...(flag("--dynamic") ? ["--dynamic"] : [])];

const code = await runScriptc([...invocation, ...forwarded]);

if (code !== 0) {
  console.error(
    "\nscriptc rejected the program. Each error is a construct it does not lower" +
      "\nyet, not a defect here; `--coverage` gives the ratio rather than the list.",
  );
} else if (!flag("--coverage")) {
  console.log(`\nCompiled → ${rel(out)} (${(await stat(out)).size} bytes)`);
}

exit(code);
