/**
 * Shared plumbing for the three `scriptc` scripts (§16, experimental).
 *
 * `compile.mjs` is the one to run; `compile-transform.mjs` and
 * `compile-bundle.mjs` are the two prototypes that established what a build
 * process can and cannot fix without touching `src/`. All three need the same
 * four things: the pinned compiler, a preflight, a tsconfig flattened out of
 * the root one, and a way to invoke `scriptc` that survives our own
 * `devEngines` gate.
 *
 * Nothing here runs on import — it is a module, not a script.
 */

import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { delimiter, join, relative } from "node:path";
import { env, exit, version } from "node:process";

/** Pinned: a compiler release must not change what these report overnight. */
export const SCRIPTC = "scriptc@0.0.34";

/** `scriptc` needs a modern host even though the binary it emits needs none. */
const MINIMUM_NODE = 24;

export const root = join(import.meta.dirname, "..");

/** Everything generated goes here, and `.gitignore` covers all of it. */
export const outDir = join(root, ".scriptc");

/**
 * `HeadersInit` is a lib.dom global, and `scriptc`'s lib set has no DOM.
 * Restated from the `Headers` constructor `@types/node` declares — an alias, so
 * the undici type and this one stay the same type rather than two lookalikes.
 */
export const GLOBALS_DTS = `// Generated by scripts/compile*.mjs — do not edit.
type HeadersInit = NonNullable<ConstructorParameters<typeof Headers>[0]>;
`;

/** Bail early rather than let `scriptc` fail obscurely on an old host. */
export function preflight() {
  const major = Number.parseInt(version.slice(1), 10);
  if (major < MINIMUM_NODE) {
    console.error(`scriptc needs Node ${MINIMUM_NODE} or newer to run; this is ${version}.`);
    exit(1);
  }

  // `SCRIPTC_CC` may name a compiler that is not on PATH as written (`zigcc` is
  // a shim scriptc resolves itself), so only the default is checked here.
  if (env.SCRIPTC_CC === undefined && !which("clang") && !which("cc")) {
    console.error("scriptc links with clang; no clang or cc on PATH.");
    exit(1);
  }
}

/**
 * The root `tsconfig.json`, inlined rather than `extends`ed — `scriptc` reads
 * `compilerOptions` without resolving `extends`, and a project config has to be
 * found at all: with none anywhere in the tree it falls back to its own narrow
 * node declarations and reports 123 `SC0001` type errors (`Property 'origin'
 * does not exist on type 'URL'`) in place of the 69 lowering diagnostics that
 * say what actually does not compile. `strictNullChecks` it refuses to run
 * without (`SC0002`); the rest of our strictness is worth about one error
 * either way. `noEmit` has to go, because `scriptc`'s program does emit.
 */
export async function flattenedTsconfig(include, overrides = {}) {
  const source = await readFile(join(root, "tsconfig.json"), "utf8");
  // tsconfig.json is JSONC; only line comments appear in ours.
  const tsconfig = JSON.parse(source.replaceAll(/^\s*\/\/.*$/gm, ""));
  delete tsconfig.compilerOptions.noEmit;
  Object.assign(tsconfig.compilerOptions, overrides);
  tsconfig.include = include;
  return `${JSON.stringify(tsconfig, undefined, 2)}\n`;
}

/** Rolldown ships inside obuild, and pnpm's store does not hoist it. */
export async function loadRolldown() {
  return import(createRequire(import.meta.resolve("obuild")).resolve("rolldown"));
}

/** Repo-relative when it can be, absolute when it cannot. */
export function rel(path) {
  const from = relative(root, path);
  return from.startsWith("..") ? path : from;
}

/**
 * Run `scriptc`, installed or through `npx`, and resolve with its exit code.
 *
 * The `npx` fallback runs from the temporary directory: `npx` reads the
 * package.json of its working directory, and ours declares
 * `devEngines.packageManager: pnpm` (§03.3), which npm honours by refusing to
 * run at all. Every path handed to `scriptc` is absolute, so the directory it
 * runs from does not matter. A local install needs no such dodge.
 */
export function runScriptc(args) {
  const local = join(root, "node_modules", ".bin", "scriptc");
  const installed = existsSync(local);
  const command = installed ? local : "npx";
  const argv = installed ? args : ["--yes", SCRIPTC, ...args];

  console.log(`\n$ ${command} ${argv.join(" ")}\n`);

  return new Promise((done, failed) => {
    const child = spawn(command, argv, {
      cwd: installed ? root : tmpdir(),
      env,
      stdio: "inherit",
    });
    child.on("error", failed);
    child.on("close", (code) => done(code ?? 1));
  });
}

function which(binary) {
  return (env.PATH ?? "")
    .split(delimiter)
    .some((dir) => dir !== "" && existsSync(join(dir, binary)));
}

/**
 * oxc's parser, which rolldown re-exports and obuild vendors. Used for its
 * *locations*, never its codegen: `transformSync` would strip the types, and the
 * types are the program `scriptc` compiles.
 */
export async function loadOxc() {
  return import(createRequire(import.meta.resolve("obuild")).resolve("rolldown/utils"));
}

/** The repo's own `tsc`, over a generated tree. Resolves with its exit code. */
export function runTsc(args) {
  const local = join(root, "node_modules", ".bin", "tsc");
  if (!existsSync(local)) {
    console.error("tsc is not installed; run `pnpm install` before --typecheck.");
    exit(1);
  }
  return new Promise((done, failed) => {
    const child = spawn(local, args, { cwd: root, env, stdio: "inherit" });
    child.on("error", failed);
    child.on("close", (code) => done(code ?? 1));
  });
}
