/**
 * The compat shim the rewrites call into, as one string.
 *
 * It is generated rather than kept as a `.ts` file so that it lands *inside*
 * the rewritten tree, where `scriptc` compiles it as part of the same program —
 * and so that it cannot be imported from `src/` by accident.
 *
 * Every helper is written twice over: it must lower under `scriptc`, and it
 * must return exactly what the expression it replaces returns, because
 * `--typecheck` compares the two. `.scriptc/spike/compat-probe.ts` is where
 * each one was checked against Node before being put here.
 */
export const COMPAT_TS = `// Generated by scripts/compile-transform.mjs — do not edit.
//
// Stand-ins for expressions scriptc has no lowering for. Each is type-identical
// to what it replaces; see scripts/transform-rules.mjs for why each is allowed.
/// <reference path="./__globals.d.ts" />

import { statSync, type Stats } from "node:fs";

/** \`URL.canParse(text)\` — the constructor lowers, the static method does not. */
export function canParse(text: string): boolean {
  try {
    new URL(text);
    return true;
  } catch {
    return false;
  }
}

/** \`url.origin\` — \`protocol\` and \`host\` both lower, and this is their definition. */
export function origin(url: URL): string {
  return \`\${url.protocol}//\${url.host}\`;
}

/**
 * \`Object.hasOwn(record, key)\`.
 *
 * Own *enumerable* keys, where \`hasOwnProperty\` answers for own keys whether
 * enumerable or not. Every caller in \`src/\` asks this of a JSON.parse result,
 * which has no non-enumerable keys, so the two agree everywhere it is used.
 */
export function hasOwn(record: object, key: string): boolean {
  return Object.keys(record).includes(key);
}

/** \`text.startsWith(search, at)\` — the second argument has no lowering. */
export function startsWithAt(text: string, search: string, at: number): boolean {
  return text.slice(at).startsWith(search);
}

/** \`rows.flat()\`, one level, which is the only depth \`src/\` asks for. */
export function flat<T>(rows: T[][]): T[] {
  const out: T[] = [];
  for (const row of rows) {
    for (const cell of row) out.push(cell);
  }
  return out;
}

/** \`statSync(path, { throwIfNoEntry: false })\` — same \`Stats | undefined\`. */
export function statOrUndefined(path: string): Stats | undefined {
  try {
    return statSync(path);
  } catch {
    return undefined;
  }
}
`;
